name: 'Slack notify action'
description: 'Slack notify action'
inputs:
  slack-channel-id:
    description: 'Slack channel id'
    required: true
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  github-repository:
    description: 'Github repository'
    required: true
  job-name:
    description: 'Job name'
    required: true
  job_status:
    description: 'Job status'
    required: true
  github-server-url:
    description: 'Github server url'
    required: true
  ref-name:
    description: 'Ref name'
    required: true
  commit-message:
    description: 'Commit message'
    required: true
  run-id:
    description: 'Run id'
    required: true
  event-name:
    description: 'Event name'
    required: true
  workflow:
    description: 'Workflow'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send notification to Slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        IMAGE_STATUS: ${{ inputs.job_status == 'success' && ':heavy_check_mark:' || ':x:' }}
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Github Action Completed - ${{ inputs.github-repository }} - ${{ inputs.job-name }} ??? ${{ github.repository }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.IMAGE_STATUS }} *${{ inputs.job_status }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ inputs.github-server-url }}/${{ inputs.github-repository }}|${{ inputs.github-repository }}>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ toJSON(inputs.commit-message) }}
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ inputs.github-server-url }}/${{ inputs.github-repository }}|${{ inputs.github-repository }}> ${{ inputs.ref-name }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Workflow run: <${{ inputs.github-server-url }}/${{ inputs.github-repository }}/actions/runs/${{ inputs.run-id }}|${{ inputs.workflow }}: ${{ inputs.event-name }}>"
                }
              },
              {
                "type": "divider"
              }
            ]
          }
