name: 'Slack notify action'
description: 'Slack notify action'
inputs:
  slack_channel_id:
    description: 'Slack channel id'
    required: true
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  context_name:
    description: 'Context name'
    required: false

runs:
  using: "composite"
  steps:
    - name: Send notification to Slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
      with:
        channel-id: ${{ inputs.slack_channel_id }}
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Github Action Completed - ${{ github.repository }} - ${{inputs.context_name}} ${{ github.job }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ job.status == 'success' && ':heavy_check_mark:' || ':x:' }} *${{ job.status }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ github.event.head_commit.message == '' && toJSON('Empty') || toJSON(github.event.head_commit.message) }}
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}> ${{ github.ref_name }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Workflow run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}: ${{ github.event_name }}>"
                }
              },
              {
                "type": "divider"
              }
            ]
          }
